server:
  port: 3000
  timeoutSecs: 10
  readTimeoutSecs: 15
  writeTimeoutSecs: 15
jwt:
  secret: secret-key
  sessionTime: 86400
db:
  dataSourceName: root:password@tcp(127.0.0.1:3306)/local_db?charset=utf8&parseTime=True&multiStatements=true
  migrate: true
  pool:
    maxOpen: 50
    maxIdle: 5
    maxLifetime: 86400