name:   CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Update Go Modules
      run: |
       go mod tidy
       go mod download
  

    - name: Run Build
      run: go build -o ./cmd/server/myapp ./cmd/server

    - name: Run Build
      run: make build  

    - name: Build the Docker image
      steps:
        - uses: actions/checkout@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Build the Docker image
          run: docker buildx build -t taniaduggal60/onepanetask:latest ./cmd/server
        - name: Push Docker Image
          run: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker image push taniaduggal60/taskonepane:latest
